# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Photon
subtitle: A Content Development System for Creatives
description: an integrated suite of tools for shining light on your work
author: i-am-phi
language: en
timezone:

formspree:
  email: phi@photon-platform.net

breadcrumb:
  display: true

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://photon-platform.net
root: /

# permalink: :year/:month/:day/:title/
permalink: :category/:title/
permalink_defaults:


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/i-am-phi/photon.git

debug: true

# Server
## Docs: https://github.com/hexojs/hexo-server
server:
  port: 3333

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: theme

# Miscellaneous
# google code for meta tag
google_analytics: set this in config.yml file
favicon: favicon.jpg

twitter:
google_plus:
fb_admins:
fb_app_id:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: /
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: article
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1 #1 lowercase 2 upercase
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

# default highlighter (disabled)
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: false

# hexo-filter-plugin (https://github.com/Jamling/hexo-filter-highlight) config
## highlight in frontend, the plugin (backend) just do some prepare work.
## you need to read the docs on https://github.com/Jamling/hexo-filter-highlight to getting start
hljs:
  enable: true #true to enable the plugin
  line_number: backend # add line_number in frontend or backend
  trim_indent: backend # trim the indent of code block to prettify output. backend or front-end (recommend)
  copy_code: false # show copy code in caption.
  label:
    left: code
    right: ':'
    copy:


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date


# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Marked markdown renderer settings
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
  modifyAnchors: ''
  autolink: true

# hexo-filer-responsive-images
# https://github.com/hexojs/hexo-filter-responsive-images
responsive_images:
  pattern: '**/*.+(png|jpg|jpeg)'
  sizes:
    th:
      width: 600
    wb:
      width: 1920
      options:
        withoutEnlargement: true

# hexo-generator-seo-friendly-sitemap
sitemap:
  path: sitemap.xml
  # tag: false
  # category: false


# hexo-beautify
beautify:
  types:
    - html
    # - css
    # - js
  exclude:
     - "*.min.css"
     - "*.min.js"
  html:
    'indent_inner_html': true
    'indent_size': 2
    'indent_with_tabs': false
    'max_preserve_newlines': 1
    # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md)
  css:
    'indent_size': 2
    'newline_between_rules': true
    'indent_with_tabs': false
    'max_pre': false
    # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md)
  js:
    'indent_size': 2
    'indent_with_tabs': false
    # More Options (https://github.com/beautify-web/js-beautify/blob/master/README.md)
