categories: Categories
category: Category
tag: Tag
tags: Tags
tagcloud: Tag Cloud
search: Search
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_articles: Recent Articles
related_articles: Related Articles
newer: Newer
older: Older
share: Share
powered_by: Powered by
rss_feed: RSS Feed
contact: Contact Us
