# Photon Theme Config file

# Header
rss: /atom.xml

# Content
excerpt_link: Read More >
excerpt_date: false
excerpt_footer: false

# include lightbox
fancybox: true

shares: true

# Sidebar
asides:
- search
- list-recent-posts
# - list-archives
- list-categories
# - list-tags
# - tagcloud

# widget behavior
archive_type: 'yearly'

# show counts for categories and tags
show_count: true
